# Generated by Django 3.2.9 on 2022-01-24 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('produtos', '0002_auto_20220117_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
