# Generated by Django 3.2.9 on 2022-01-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='qted',
        ),
    ]
