# Generated by Django 3.2.9 on 2022-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(to='produtos.Categoria'),
        ),
    ]
