# Generated by Django 3.2.9 on 2022-05-11 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'saida'), ('1', 'entrada')], max_length=50, verbose_name='TIPO')),
                ('id_moviemnto', models.PositiveSmallIntegerField(blank=True, max_length=1, null=True)),
                ('movimento', models.CharField(max_length=35)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forma_pg', models.CharField(choices=[('0', 'ESPECIE'), ('1', 'CARTAO'), ('2', 'PIX'), ('3', 'DEPOSITO')], max_length=50, verbose_name='Forma de pagamento')),
                ('val_cartao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_cartao_liq', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_pix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_transferencia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_especie', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendendor')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
