# Generated by Django 3.2.9 on 2022-01-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_itemsvenda_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
