# Generated by Django 3.2.9 on 2022-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_alter_venda_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descontos_Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desconto', models.CharField(max_length=25)),
            ],
        ),
    ]
