# Generated by Django 3.2.9 on 2022-02-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_descontos_kits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descontos_kits',
            old_name='desconto',
            new_name='descricao',
        ),
    ]
