# Generated by Django 3.2.9 on 2022-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_rename_desconto_descontos_kits_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descontos_kits',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
